CLK_PERIOD = 50 # ns (20 MHz)

# Regmap registers
RM_TIMER_CTL      = 0x00
RM_TIMER_TOP      = 0x01
RM_TIMER_CLK_DIV  = 0x02
RM_TIMER_CAPT_CTL = 0x03

RM_GPIO_RDATA     = 0x04
RM_GPIO_WDATA     = 0x05
RM_GPIO_DIR       = 0x06

RM_LFSR_POLY      = 0x07
RM_LFSR_CTL       = 0x08
RM_LFSR_IDATA     = 0x09

RM_TIMER_PWM0_TOP = 0x0a
RM_TIMER_PWM1_TOP = 0x0b
RM_TIMER_PWM2_TOP = 0x0c
RM_TIMER_PWM3_TOP = 0x0d

RM_TIMER_CAPTURE0 = 0x0e
RM_TIMER_CAPTURE1 = 0x0f
RM_TIMER_CAPTURE2 = 0x10
RM_TIMER_CAPTURE3 = 0x11
RM_TIMER_CAPTURE4 = 0x12
RM_TIMER_CAPTURE5 = 0x13
RM_TIMER_CAPTURE6 = 0x14
RM_TIMER_CAPTURE7 = 0x15

# ui_in signal indices
TIMER_CAPTURE0 = 0
TIMER_CAPTURE1 = 1
TIMER_CAPTURE2 = 2
TIMER_CAPTURE3 = 3
TIMER_CAPTURE4 = 4
TIMER_CAPTURE5 = 5
TIMER_CAPTURE6 = 6
TIMER_CAPTURE7 = 7

# uio signal indices
SPI_MSEL = 0 
SPI_MOSI = 1
SPI_MISO = 2
SPI_MCLK = 3
GPIO0 = 4
GPIO1 = 5
GPIO2 = 6
GPIO3 = 7

# uo_out signal indices
TIMER_PWM0 = 0
TIMER_PWM1 = 1
TIMER_PWM2 = 2
TIMER_PWM3 = 3
LFSR_OUT = 4

# SPI related
SPI_CLK_PERIOD = 100 # ns
SPI_SYNC_STAGES = 2

SPI_RW_BIT = 7
SPI_WRITE_MODE = 1
SPI_READ_MODE = 0

# GPIO related
GPIO_COUNT = 4
GPIO_MSK = 0xf0
# Directions:
# '1' -- output
# '0' -- input

# LFSR related
LFSR_EN = 0
LFSR_LOAD = 1
LFSR_INIT_STATE = 0x01
LFSR_MAX_N_POLYNOME = 0x63
LFSR_WIDTH = 8
LFSR_MSK = 0xff

# Timer related
TIMER_WIDTH = 8
TIMER_MSK = 0xff
TIMER_PWM_COUNT = 4
TIMER_CAPTURE_COUNT = 8
TIMER_CAPT_SYNC_STAGES = 2

TIMER_EN          = 0
TIMER_UP_DOWN     = 1
TIMER_EN_PWM      = 2
TIMER_EN_CAPT     = 3
TIMER_RST_ON_TOP  = 4

CAPT_RISING_EDGE = 1
CAPT_FALLING_EDGE = 0


